### ISSUE TITLE
Certain Videos Doesn't play

### ISSUE THREAD

**Issue by FireMasterK** [deep-gaurav/rusty_pipe_front#1]
Hi there,

Awesome work on the project! It's definitely a great alternative to Invidious!

I love that all processing is done on the client with WASM, it's definitely a unique way to shift load of the servers.

Video URL: https://rustypipe.deepraven.co/video/s1-D8UOq7iA

In the video, the stream returns 403.
I've also tried playing the video on Invidious, it seems to give a 403 error there too.
But, the video does play properly on NewPipe.

The video is not region restricted: http://polsy.org.uk/stuff/ytrestrict.cgi?ytid=s1-D8UOq7iA&auth=09a2824cb967e7e6e686941a99b26150

I'd love to help investigate!

**Comment by deep-gaurav** [comment]
Hi, music videos from official channel are encrypted, rustypipe can decrypt video url but in these videos url is linked to ip address too, and ip address in web version i.e rustypipe.deepraven.co is of vercel serverless function, so it can't be played on the client device.
There is no way to play these in web version, but no cors proxy is used in desktop version, so if you're on linux you can download latest appimage from release page and it'll play all videos.
Windows version currently does not work.
I'll also add android version soon.

But I am not able to find any solution to make it work in web version

**Comment by FireMasterK** [comment]
Awesome! I just got my friend to install the AppImage on linux, it says it plays fine but for some reason he can't make the video full-screen. That's an unrelated issue tho. 

I just found out how to fix the issue on Invidious, just enable "Proxy videos" in settings and everything starts working again. Would it be possible to add a similar setting/feature to Rusty Pipe?

**Comment by deep-gaurav** [comment]
No I don't think something similar can be done, as parsing is done on client side and cors proxy being used is a serverless function.
And serverless function has hard limit of maximum content size of 5MB, most videos are more than 5MB so serverless function won't be able to proxy it.

I'm not exactly sure how invidious does it, but most probably it's done by downloading complete video on invidious server and serving from it.

**Comment by deep-gaurav** [comment]
Update,
I added a video proxy in rustypipe graphql server, site will use it now if a video can't be played.
Every video should play now, if it's not age or region restricted

**Comment by FireMasterK** [comment]
Awesome! It works perfectly now!
